typofix:laf函数调用时，弹出文字错误
labring/FastGPT pull request #2951
Opened 2024-10-17 08:55 UTC by zhengkai6

laf函数调用，新增/编辑输出时，显示错误，目前显示为新增/编辑输入

如下图
![image](https://github.com/user-attachments/assets/fa258251-0cdf-4007-be21-78b16887f5f8)
![image](https://github.com/user-attachments/assets/68ddb03a-8fa8-47f9-ad90-8e40e8a8c027)

2024-10-17 09:04 UTC, zhengkai6 commented
@c121914yu  pls help review, thx

2024-10-17 10:39 UTC, c121914yu commented
ts 有个报错

2024-10-18 03:30 UTC, zhengkai6 commented
> ts 有个报错，需要检查下。

已在飞书群里反馈  有同事说跟进一下

2024-10-18 08:57 UTC, newfish-cmyk reviewed
这个改的不太对，这个改运行逻辑了，应该改下文案就行
可以看下这个文件
FastGPT/projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/FieldEditModal.tsx#L119
<img width="731" alt="image" src="https://github.com/user-attachments/assets/f234d948-ebf3-4ca8-8689-beced7bbdfe1">
把 input 的文案改成 output 就行

2024-10-18 08:57 UTC, newfish-cmyk requested changes
这个改的不太对，这个改运行逻辑了，应该改下文案就行
可以看下这个文件
FastGPT/projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/FieldEditModal.tsx#L119
<img width="731" alt="image" src="https://github.com/user-attachments/assets/f234d948-ebf3-4ca8-8689-beced7bbdfe1">
把 input 的文案改成 output 就行

2024-10-22 00:45 UTC, zhengkai6 commented
> 这个改的不太对，这个改运行逻辑了，应该改下文案就行 可以看下这个文件 FastGPT/projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/FieldEditModal.tsx#L119 <img alt="image" width="731" src="https://private-user-images.githubusercontent.com/71265218/377798758-f234d948-ebf3-4ca8-8689-beced7bbdfe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NTgyMDYsIm5iZiI6MTcyOTU1NzkwNiwicGF0aCI6Ii83MTI2NTIxOC8zNzc3OTg3NTgtZjIzNGQ5NDgtZWJmMy00Y2E4LTg2ODktYmVjZWQ3YmJkZmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAwNDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMTY3MWVmYjRlNzBkNWYyNThlZGZiYTU2NDEwMDVhMDljNDMyZjk3ZDk0NGIzOGZiNDk5NjY1OTE2OTZhNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qwgJkJA41lZCxgDLCAttFTDtvAuEfx8HDZT3BO_Up4E"> 把 input 的文案改成 output 就行

已重新提交 多谢

2024-10-22 00:49 UTC, newfish-cmyk approved these changes

2024-10-22 00:49 UTC, newfish-cmyk commented
thx！

2024-10-22 00:50 UTC, merged