add bing search plugins
labring/FastGPT pull request #2970
Opened 2024-10-22 11:14 UTC by Patrickill

2024-10-22 13:52 UTC, c121914yu commented on packages/web/components/common/Icon/icons/core/workflow/template/bing.svg
搞个彩色的

2024-10-23 07:51 UTC, newfish-cmyk requested changes

2024-10-23 07:51 UTC, newfish-cmyk commented on packages/plugins/src/bing/template.json
> +            "description": "Google搜索key",
这下面咋还都是 Google 😂

2024-10-23 08:43 UTC, Patrickill commented on packages/plugins/src/bing/template.json
> +            "description": "Google搜索key",
在Google插件的基础上改的忘记改了🤯

2024-10-23 14:44 UTC, c121914yu approved these changes

2024-10-23 14:45 UTC, merged